// Vietnamese version

window.commonQuestions = [
  {
    id: 1,
    question: "Bạn có thích làm việc tại Nhật Bản không?",
    image: "/interview-quiz-images/q1.jpg",
    choices: [
      {
        text: "Vâng, tôi rất quan tâm",
        score: 1.0,
        emoji: "⭕",
        explanation: "Sự quan tâm mạnh mẽ đến việc làm việc tại Nhật Bản là yếu tố quan trọng nhất. Sự quan tâm đến ngôn ngữ và văn hóa Nhật Bản sẽ mang lại cho bạn động lực học tiếng Nhật và văn hóa Nhật Bản, đồng thời tiếp thêm sức mạnh để bạn vượt qua ngay cả những tình huống khó khăn. Các công ty Nhật Bản rất coi trọng không chỉ kỹ năng và kinh nghiệm mà còn cả mong muốn được làm việc tại đất nước này.\n\nMỗi người đều có những lý do khác nhau để quan tâm. Muốn học công nghệ Nhật Bản, có cuộc sống ổn định, hỗ trợ gia đình, thăng tiến trong sự nghiệp,… Dù vì lý do gì thì sự nhiệt tình đó đều dẫn đến tinh thần nghiêm túc với công việc. Trong cuộc phỏng vấn, bạn sẽ được đánh giá nhiều hơn nếu bạn có thể giải thích được lý do cụ thể.\n\nSở thích làm việc tại Nhật Bản cũng ảnh hưởng đến tỷ lệ giữ chân lâu dài. Những ai quan tâm có thể tiếp tục suy nghĩ: “Tôi muốn cố gắng hết sức ở Nhật Bản”, ngay cả khi gặp khó khăn. Mặt khác, những người ít quan tâm đến việc du học có thể ngay lập tức cân nhắc việc trở về quê hương khi gặp khó khăn dù là nhỏ nhất. Câu trả lời cho câu hỏi này là yếu tố quyết định lớn trong việc tuyển dụng, vì các công ty đang tìm kiếm những người sẽ gắn bó lâu dài với họ.\n\nNhững người trả lời được câu hỏi này sẽ tạo được ấn tượng tốt nhất trong buổi phỏng vấn và có cơ hội được tuyển dụng rất cao. Điều này sẽ được đánh giá cao là bằng chứng cho thấy bạn đang cân nhắc nghiêm túc việc làm việc tại Nhật Bản."
      },
      {
        text: "Tôi khá quan tâm",
        score: 0.7,
        emoji: "🟡",
        explanation: "Cụm từ \"so-so\" trong tiếng Nhật đôi khi được hiểu là \"không mạnh đến thế\". Ngay cả khi bạn thực sự quan tâm, có thể bạn chỉ trả lời một cách khiêm tốn nhưng người phỏng vấn lại cảm thấy hơi khó chịu, tự hỏi liệu động cơ của người này có phải là thật lòng hay không.\n\nNếu bạn chọn câu trả lời này, hãy nhớ đưa ra lời giải thích bổ sung trong cuộc phỏng vấn. Bạn có thể cải thiện đánh giá của mình bằng cách truyền đạt những chi tiết cụ thể mà bạn quan tâm, chẳng hạn như ``Tôi quan tâm đến 〇〇 ở Nhật Bản'' hoặc ``Tôi muốn học △△ ở Nhật Bản.''\n\nVăn hóa doanh nghiệp Nhật Bản ưa chuộng những tuyên bố rõ ràng về ý định hơn là nói giảm nhẹ. Đặc biệt trong một cuộc phỏng vấn, điều quan trọng là phải thể hiện rõ ràng cảm xúc của mình. Bạn sẽ để lại ấn tượng tốt hơn nếu trả lời một cách tự tin: “Tôi rất quan tâm”.\n\nTuy nhiên, câu trả lời này sẽ không dẫn đến sự từ chối. Hãy thể hiện sự nhiệt tình của bạn trong các câu hỏi khác và bạn sẽ được đánh giá tổng thể. Điều quan trọng là truyền đạt mong muốn làm việc tại Nhật Bản của bạn theo một cách nào đó."
      },
      {
        text: "Tôi có chút quan tâm",
        score: 0.5,
        emoji: "🟡",
        explanation: "Từ \"một chút\" biểu thị mức độ quan tâm thấp. Người phỏng vấn lo lắng, ``Người này có thực sự muốn làm việc ở Nhật Bản không?'' ``Liệu anh ta có bỏ việc ngay nếu có lựa chọn tốt hơn không?''\n\nCó nhiều lý do khác nhau để đưa ra câu trả lời này. Bạn chưa biết nhiều về Nhật Bản, bạn đang cân nhắc các quốc gia khác, gia đình bạn phản đối, v.v. Tuy nhiên, trong các cuộc phỏng vấn, bạn nên tránh những cách diễn đạt tiêu cực như “một chút”. Nếu bạn thực sự không chắc chắn, tốt hơn hết bạn nên phân loại cảm xúc của mình trước rồi mới áp dụng.\n\nTuy nhiên, nếu bạn thành thật trả lời “một chút”, người phỏng vấn có thể giải thích chi tiết hơn. Bạn có thể tăng thêm sự quan tâm của mình thông qua đối thoại, chẳng hạn như “Bạn lo lắng về điều gì?” và “Có điều gì bạn muốn biết về cuộc sống ở Nhật Bản không?”\n\nNếu bạn đã đưa ra câu trả lời này, hãy nhớ cho mình một cơ hội để bù đắp trong cuộc phỏng vấn. Bạn có thể cải thiện sự đánh giá của mình bằng cách nói những điều như, “Lúc đầu tôi hơi lo lắng, nhưng sau khi nghe về công ty của bạn, tôi thực sự muốn làm việc cho công ty của bạn”."
      },
      {
        text: "tôi không quan tâm lắm",
        score: 0.0,
        emoji: "❌",
        explanation: "Câu trả lời này gây tử vong trong một cuộc phỏng vấn. Người phỏng vấn không thể hiểu tại sao một người không quan tâm đến việc làm việc ở Nhật Bản lại đến phỏng vấn. Ngay cả khi lý do của bạn là “vì gia đình tôi bảo tôi làm như vậy” hay “vì tôi không còn lựa chọn nào khác”, nếu bạn thành thật về điều đó thì cơ hội được tuyển dụng của bạn gần như bằng không.\n\nCác công ty tránh được rủi ro tuyển dụng những người không có động lực. Có số liệu cho thấy những người không có hứng thú thì học nghề chậm, bỏ việc nhanh và dễ gặp rắc rối hơn. Đặc biệt khi tuyển người nước ngoài, gánh nặng đối với công ty rất lớn như thủ tục visa, hỗ trợ cuộc sống hàng ngày nên họ chỉ muốn thuê những người chắc chắn sẽ làm việc lâu dài cho họ.\n\nNếu bạn không thực sự quan tâm đến Nhật Bản thì không cần phải ép mình nộp đơn. Tôi sẽ hạnh phúc hơn nếu tôi tìm kiếm một công việc khác ở một quốc gia khác. Mặt khác, nếu bạn quan tâm nhưng có nhiều lo lắng, hãy thành thật về điều đó trong cuộc phỏng vấn. Một công ty tốt sẽ cung cấp cho bạn thông tin giúp bạn giảm bớt lo lắng.\n\nCâu trả lời này cực kỳ khó khắc phục, cho dù các khả năng khác của bạn có tốt đến đâu. Trong cuộc phỏng vấn, hãy chắc chắn chọn câu trả lời tích cực."
      },
    ]
  },
  {
    id: 2,
    question: "Bạn đang học tiếng Nhật à?",
    image: "/interview-quiz-images/q2.jpg",
    choices: [
      {
        text: "Vâng, tôi học mỗi ngày",
        score: 1.0,
        emoji: "⭕",
        explanation: "Thái độ học tiếng Nhật hàng ngày của bạn được đánh giá cao. Điều này không chỉ chứng tỏ khả năng ngôn ngữ của bạn mà còn chứng tỏ bạn là người có thể nỗ lực và có thể tiếp tục nỗ lực hướng tới mục tiêu của mình. Thái độ nghiêm túc này là điều mà các công ty Nhật Bản đánh giá cao nhất.\n\nCó nhiều cách khác nhau để học tiếng Nhật. Đến trường, tham gia lớp học trực tuyến, học trên ứng dụng, luyện nói với người Nhật, xem phim truyền hình Nhật Bản, v.v. Trong buổi phỏng vấn, bạn sẽ tạo ấn tượng tốt hơn nếu có thể giải thích rõ ràng phương pháp học tập cụ thể của mình. “Tôi học 30 phút mỗi ngày bằng ứng dụng”, “Tôi đến lớp học tiếng Nhật hai lần một tuần” v.v.\n\nNgoài ra, hãy trung thực về trình độ tiếng Nhật hiện tại của bạn. “Tôi có thể đọc Hiragana và Katakana”, “Tôi có thể trò chuyện đơn giản”, “Tôi có JLPT N4”, v.v. Ngay cả khi nó không hoàn hảo, điều quan trọng là phải tiếp tục học hỏi.\n\nNhững người trả lời câu hỏi này được kỳ vọng sẽ tiếp tục học hỏi những điều mới ngay cả sau khi gia nhập công ty. Bạn có thể tin tưởng rằng chúng tôi sẽ tích cực học không chỉ tiếng Nhật mà còn cả kỹ năng làm việc."
      },
      {
        text: "tôi đang học một chút",
        score: 0.7,
        emoji: "🟡",
        explanation: "Một câu trả lời như “Tôi đang học một chút” không tệ, nhưng thật khó để truyền tải sự nhiệt tình của bạn so với “mỗi ngày”. Người phỏng vấn có thể thắc mắc: \"Người này nghiêm túc đến mức nào?\"\n\nNếu bạn chọn trả lời câu hỏi này, vui lòng nói rõ ý bạn khi nói \"một chút\". Người phỏng vấn sẽ cảm thấy thoải mái nếu bạn nói với họ về thời gian và tần suất cụ thể, chẳng hạn như “Tôi học một giờ hai lần một tuần” hoặc “Tôi bận công việc nhưng tôi học vào cuối tuần”.\n\nNó cũng có hiệu quả để nói về kế hoạch học tập trong tương lai của bạn. Nếu bạn thể hiện thái độ tích cực, chẳng hạn như “Bây giờ tôi đang học một chút, nhưng tôi sẽ học nghiêm túc hơn khi đậu” hoặc “Tôi dự định học chuyên sâu trước khi gia nhập công ty”, bạn có thể cải thiện đánh giá của mình.\n\nĐiều quan trọng là phải tiếp tục học tiếng Nhật ngay cả sau khi gia nhập công ty. Thật khó để vừa học vừa làm, nhưng càng cải thiện tiếng Nhật thì phạm vi công việc bạn có thể làm càng rộng và mức lương sẽ càng cao. Tăng thời gian học của bạn lên từng chút một, từ \"một chút\" đến \"mỗi ngày\"."
      },
      {
        text: "tôi đang đi học",
        score: 0.5,
        emoji: "🟡",
        explanation: "Câu trả lời “Bây giờ tôi sẽ học” là thành thật nhưng nó tạo ấn tượng rằng bạn chưa chuẩn bị. Người phỏng vấn lo lắng “Người này có thực sự sẵn sàng làm việc ở Nhật Bản không?” Đặc biệt, việc chưa bắt đầu học vào thời điểm phỏng vấn có thể được hiểu là thiếu kế hoạch.\n\nTuy nhiên, câu trả lời này không hoàn toàn tiêu cực. Nếu bạn nhấn mạnh rằng “Tôi chưa bắt đầu, nhưng tôi có động lực”, bạn có cơ hội phục hồi. Trong cuộc phỏng vấn, hãy nhớ giải thích kế hoạch cụ thể của bạn, chẳng hạn như khi nào bạn sẽ bắt đầu học, bạn sẽ học như thế nào và trình độ bạn hướng tới.\n\nĐiều quan trọng nữa là phải thành thật về lý do bạn không học. ``Gần đây tôi đã quyết định đi làm việc ở Nhật Bản'', ``Tôi bận công việc đến mức không có thời gian'', v.v. Nếu sau đó bạn thể hiện rằng bạn quyết tâm học tập nghiêm túc từ bây giờ, người phỏng vấn có thể hiểu.\n\nTốt nhất, chúng tôi khuyên bạn nên bắt đầu học tiếng Nhật ít nhất một chút trước cuộc phỏng vấn. Nếu bạn có thành tích học tập trong một hoặc hai tuần, bạn có thể trả lời: \"Tôi đang học\"."
      },
      {
        text: "không học",
        score: 0.3,
        emoji: "🟢",
        explanation: "Cần phải có can đảm để thành thật trả lời: “Tôi không học”. Tuy nhiên, nó sẽ là một điểm tiêu cực lớn trong cuộc phỏng vấn. Học tiếng Nhật là điều cần thiết để làm việc tại Nhật Bản và không học sẽ bị hiểu là “không chuẩn bị” hoặc “không có động lực”.\n\nNếu bạn chọn câu trả lời này, hãy nhớ giải thích lý do và kế hoạch tương lai của bạn. Người phỏng vấn sẽ hiểu nếu bạn có lý do chính đáng, chẳng hạn như ``Tôi không có cơ hội học tiếng Nhật ở quê nhà'' hoặc ``Tôi không thể đến trường vì lý do tài chính.''\n\nSau đó, hãy nói cụ thể về việc bạn sẽ học tập như thế nào sau khi vào công ty. Bạn có thể truyền đạt động lực của mình bằng cách đặt ra các mục tiêu rõ ràng, chẳng hạn như ``Tôi sẽ nghiêm túc tham gia khóa đào tạo tiếng Nhật của công ty'' ``Tôi sẽ tự học 2 giờ mỗi ngày'' và ``Tôi sẽ đậu JLPT N5 sau 3 tháng.''\n\nCó những công việc bạn có thể được tuyển dụng ngay cả khi bạn không có tiếng Nhật. Đặc biệt, có những vị trí tuyển dụng không yêu cầu tiếng Nhật, nhất là những công việc đơn giản ở nhà máy hoặc nơi làm việc có nhiều người nước ngoài. Tuy nhiên, bạn nên hiểu rằng lựa chọn của bạn sẽ bị thu hẹp hơn và mức lương của bạn sẽ thấp hơn những người nói được tiếng Nhật."
      },
    ]
  },
  {
    id: 3,
    question: "Bạn có thể tuân theo văn hóa và quy tắc của Nhật Bản không?",
    image: "/interview-quiz-images/q3.jpg",
    choices: [
      {
        text: "Vâng, tôi sẽ tôn trọng và bảo vệ bạn.",
        score: 1.0,
        emoji: "⭕",
        explanation: "Thái độ tôn trọng văn hóa và quy định của Nhật Bản là một trong những yếu tố quan trọng nhất khi tuyển dụng người nước ngoài. Dù một người có năng lực đến đâu, những người không tôn trọng văn hóa sẽ gây ra vấn đề tại nơi làm việc và làm xấu đi mối quan hệ với những người xung quanh. Mặt khác, những người tôn trọng văn hóa sẽ nhận được sự giúp đỡ từ những người xung quanh ngay cả khi ngôn ngữ của họ có chút bất tiện.\n\nVăn hóa và quy tắc của Nhật Bản có thể khác với đất nước của bạn về nhiều mặt, chẳng hạn như đúng giờ, tôn trọng các mối quan hệ thứ bậc, duy trì sự sạch sẽ và quan tâm đến môi trường xung quanh. Tuy nhiên, thay vì chỉ trích những điều “khác biệt” là “sai”, điều quan trọng là phải chấp nhận chúng như “điều cần học hỏi”.\n\nTrong cuộc phỏng vấn, bạn nên nói về những quy tắc cụ thể mà bạn biết. ``Tôi nghe nói rằng điều quan trọng là phải đúng giờ'', ``Tôi coi trọng lời chào hỏi'' và ``Tôi tôn trọng việc phân loại rác.'' Nếu bạn thể hiện rằng bạn đã nghiên cứu trước về văn hóa Nhật Bản, sự chuẩn bị của bạn sẽ được đánh giá.\n\nNhững người trả lời được câu hỏi này sẽ được đánh giá là người có khả năng thích ứng nhanh với môi trường làm việc và xây dựng được mối quan hệ tốt với đồng nghiệp Nhật Bản. Thái độ tôn trọng văn hóa là nền tảng để làm việc lâu dài tại Nhật Bản."
      },
      {
        text: "Vâng, tôi sẽ cố gắng",
        score: 0.7,
        emoji: "🟡",
        explanation: "Câu trả lời “Tôi sẽ nỗ lực” là tích cực, nhưng nghe có vẻ kém tự tin hơn một chút so với “Tôi sẽ tôn trọng và bảo vệ bạn”. Người phỏng vấn có thể cảm thấy hơi lo lắng và tự hỏi: “Người này thực sự có thể tự bảo vệ mình được không?”\n\nNếu bạn chọn câu trả lời này, hãy trung thực và giải thích lý do tại sao nỗ lực này là cần thiết. Nếu bạn thể hiện thái độ khiêm tốn và tích cực, chẳng hạn như “Lúc đầu tôi có thể bối rối vì văn hóa khác với quê hương tôi, nhưng tôi sẽ học tập chăm chỉ” hoặc “Nếu tôi không hiểu điều gì đó, tôi sẽ đặt câu hỏi ngay lập tức”, đánh giá của bạn sẽ được cải thiện.\n\nVăn hóa và quy tắc của Nhật Bản ban đầu có vẻ khó khăn. Tuy nhiên, nhiều người nước ngoài sẽ quen dần sau 2-3 tháng. Điều quan trọng là “ý chí bảo vệ”. Ngay cả khi bạn không hoàn hảo, nếu bạn thể hiện rằng mình đang nỗ lực thì các đồng nghiệp Nhật Bản sẽ giúp đỡ bạn.\n\nNgoài ra, từ ``cố gắng hết sức'' cũng được sử dụng ở Nhật Bản có nghĩa là 'cố gắng hết sức'. Người phỏng vấn nhìn nhận bạn như thế nào tùy thuộc vào nét mặt và thái độ của bạn. Nếu bạn nói “Tôi sẽ cố gắng hết sức” với sự tự tin và vẻ mặt nghiêm túc, bạn sẽ tạo được ấn tượng tốt."
      },
      {
        text: "nó có thể hơi khó khăn một chút",
        score: 0.5,
        emoji: "🟡",
        explanation: "Trả lời “Có thể khó” có thể là trung thực nhưng nó lại là một tiêu cực lớn trong một cuộc phỏng vấn. Các công ty không thể thuê những người không thể tuân thủ văn hóa và quy tắc. Điều này là do nó có thể gây rắc rối.\n\nNếu bạn đưa ra câu trả lời này, hãy nhớ giải thích cụ thể điều gì là khó khăn và thảo luận cách khắc phục nó. ``Ở quê hương, tôi rất lỏng lẻo về thời gian, nhưng ở Nhật tôi mang theo hai chiếc đồng hồ nên không bao giờ bị trễ.'' ``Tôi nghe nói rằng hệ thống phân cấp rất nghiêm ngặt, nhưng tôi hiểu rằng điều quan trọng là phải tôn trọng cấp trên.''\n\nNhững điểm đặc biệt khó khăn trong văn hóa Nhật Bản ở mỗi người là khác nhau. Đúng giờ, sử dụng kính ngữ, ý định thực sự và tatemae, mối quan hệ thứ bậc, v.v. Suy nghĩ trước về những gì có thể khó khăn và chuẩn bị các biện pháp đối phó sẽ giúp bạn đưa ra lời giải thích thuyết phục trong cuộc phỏng vấn.\n\nTuy nhiên, nếu nói “khó khăn” quá nhiều sẽ bị đánh giá là “người này không thể thích nghi được”. Dù thừa nhận rằng sẽ khó khăn nhưng điều quan trọng là phải thể hiện ý chí kiên cường và nói: “Nhưng, tôi sẽ tuyệt đối bảo vệ nó”."
      },
      {
        text: "Tôi muốn trân trọng con đường của quê hương tôi.",
        score: 0.0,
        emoji: "❌",
        explanation: "Câu trả lời này là câu bạn nên tránh nhất trong một cuộc phỏng vấn. Việc tôn trọng văn hóa quê hương là điều tuyệt vời nhưng nếu muốn làm việc tại Nhật Bản, bạn cần phải tuân thủ các quy định của Nhật Bản. Nói rằng bạn ưu tiên “đường lối của quê hương” cũng giống như tuyên bố rằng “bạn sẽ không tuân theo các quy tắc của Nhật Bản”.\n\nCác công ty Nhật Bản tôn trọng sự đa dạng nhưng mong muốn mọi người tuân theo các quy tắc cơ bản (đúng giờ, quy tắc an toàn, quản lý vệ sinh, v.v.). Nếu “cách sống ở quê hương” mâu thuẫn với những quy tắc này, các công ty không thể tuyển dụng bạn.\n\nNếu bạn thực sự muốn bảo tồn văn hóa của quê hương mình, hãy thực hành nó bên ngoài công việc (trong cuộc sống riêng tư, vào những ngày nghỉ và khi giao lưu với bạn bè ở quê hương). Điều quan trọng là phải đạt được sự cân bằng giữa việc tuân thủ các quy định của Nhật Bản khi làm việc và việc tận hưởng văn hóa quê hương sau giờ làm việc.\n\nNếu bạn đưa ra câu trả lời này thì sẽ rất khó phục hồi. Nếu bạn thực sự nghĩ như vậy, bạn có thể muốn xem xét lại việc làm việc tại Nhật Bản. Mặt khác, nếu bạn vừa nói sai điều gì đó thì hãy sửa ngay. Nếu bạn diễn đạt lại bằng cách nói, “Tôi coi trọng văn hóa quê hương tôi, nhưng tôi sẽ luôn tuân thủ các quy định của Nhật Bản”, thì vẫn có một chút khả năng."
      },
    ]
  },
  {
    id: 4,
    question: "Nếu tôi gặp vấn đề, tôi có thể nói chuyện với ai đó không?",
    image: "/interview-quiz-images/q4.jpg",
    choices: [
      {
        text: "Vâng, tôi sẽ nói chuyện với bạn ngay",
        score: 1.0,
        emoji: "⭕",
        explanation: "Những người bạn có thể nhờ cậy ngay khi gặp vấn đề là những người đáng tin cậy nhất ở nơi làm việc. Bằng cách tìm kiếm sự giúp đỡ sớm thay vì giữ vấn đề trong lòng, bạn có thể ngăn chặn những vấn đề nhỏ biến thành vấn đề lớn. Tại nơi làm việc ở Nhật Bản, quy tắc cơ bản là \"báo cáo, giao tiếp và tham khảo ý kiến ​​(horenso)\" và thái độ này rất được đánh giá cao.\n\nĐặc biệt, lao động nước ngoài thường gặp nhiều khó khăn hơn lao động Nhật Bản do sự khác biệt về ngôn ngữ, văn hóa. Không hiểu được những chỉ dẫn trong công việc, gặp khó khăn trong cuộc sống hàng ngày, cảm thấy không khỏe, gặp rắc rối trong các mối quan hệ, v.v. Nếu chịu đựng những điều này một mình, bạn sẽ bị căng thẳng và trường hợp xấu nhất là bạn sẽ đột ngột nghỉ việc.\n\nKhông có gì xấu hổ khi xin lời khuyên. Đúng hơn, họ được đánh giá là “người này có kỹ năng giải quyết vấn đề tốt” và “người này giỏi giao tiếp”. Các công ty Nhật Bản thường có hệ thống hỗ trợ người lao động nước ngoài và rất mong nhận được phản hồi từ bạn.\n\nNhững người trả lời được câu hỏi này có nhiều khả năng được tuyển dụng như những người có thể xử lý thích hợp các tình huống khó khăn và làm việc ổn định trong thời gian dài."
      },
      {
        text: "Vâng, tôi sẽ thảo luận",
        score: 0.7,
        emoji: "🟡",
        explanation: "Một câu trả lời như \"Tôi sẽ tham khảo ý kiến ​​của bạn\" không tệ, nhưng việc thiếu từ \"ngay lập tức\" tạo cảm giác hơi bị động. Người phỏng vấn có thể hơi lo lắng và suy nghĩ, “Liệu người này có để yên vấn đề không?”\n\nNếu bạn chọn câu trả lời này, hãy nhớ giải thích cụ thể thời điểm bạn muốn tham khảo ý kiến ​​​​của ai đó trong cuộc phỏng vấn. Nếu bạn đưa ra những ví dụ cụ thể như “Tôi sẽ nói chuyện với bạn nếu tôi không hiểu điều gì đó”, “Tôi sẽ nói chuyện với bạn nếu tôi cảm thấy không khỏe” hoặc “Tôi sẽ nói chuyện với bạn nếu tôi gặp vấn đề”, đánh giá của bạn sẽ được cải thiện.\n\nBạn cũng nên suy nghĩ xem nên tham khảo ý kiến ​​của ai. Cấp trên trực tiếp, nhân sự nhân sự, cấp cao, đồng nghiệp, bộ phận hỗ trợ nước ngoài, v.v. Thông tin liên hệ khác nhau tùy thuộc vào công ty, vì vậy điều quan trọng là phải kiểm tra trước khi gia nhập công ty.\n\nTại nơi làm việc của người Nhật, thời điểm tư vấn cũng rất quan trọng. Tốt nhất, bạn nên tìm kiếm lời khuyên ngay khi có vấn đề phát sinh, nhưng bạn cũng nên cân nhắc những việc như tránh những lúc sếp bận và bắt đầu với những vấn đề cấp bách nhất trước tiên. Bạn càng thể hiện rằng bạn hiểu những chi tiết này thì việc đánh giá của bạn sẽ càng tốt hơn."
      },
      {
        text: "Tôi muốn tự mình giải quyết",
        score: 0.5,
        emoji: "🟡",
        explanation: "Thái độ “Tôi muốn tự mình giải quyết vấn đề” là một điều tuyệt vời vì nó mang lại cho bạn cảm giác độc lập. Tuy nhiên, tại nơi làm việc ở Nhật Bản, việc chỉ giải quyết vấn đề có thể bị coi là tiêu cực. Đặc biệt đối với người lao động nước ngoài, có rất nhiều vấn đề họ không thể tự mình giải quyết do sự khác biệt về ngôn ngữ, văn hóa.\n\nNếu bạn đưa ra câu trả lời này, hãy thêm vào cuộc phỏng vấn: “Nếu bạn không thể giải quyết vấn đề, tôi sẽ nói chuyện với bạn”. Bạn có thể thể hiện thái độ cân bằng bằng cách nói: “Tôi sẽ tự nghĩ về việc đó trước, nhưng nếu tôi không hiểu, tôi sẽ nói chuyện với bạn ngay”.\n\nThực tế, ở nơi làm việc, bạn cần cả khả năng tự giải quyết vấn đề và khả năng tư vấn phù hợp. Người lý tưởng là người có thể tự mình giải quyết những vấn đề đơn giản và tham khảo ý kiến ​​của người khác về những vấn đề khó khăn hoặc những vấn đề mà họ gặp khó khăn khi đưa ra quyết định.\n\nNgoài ra, nếu lý do bạn muốn tự mình giải quyết vấn đề là vì khiêm tốn cảm thấy rằng bạn không muốn gây rắc rối cho người khác thì điều đó thật tuyệt. Tuy nhiên, tại nơi làm việc của người Nhật, việc xin lời khuyên không phải là điều phiền toái mà được coi là có tinh thần trách nhiệm và có khả năng làm việc theo nhóm. Nếu bạn có thể chứng tỏ rằng bạn hiểu điều này, bạn có thể cải thiện xếp hạng của mình."
      },
      {
        text: "Tôi không giỏi tư vấn",
        score: 0.3,
        emoji: "🟢",
        explanation: "Câu trả lời “Tôi không thích đưa ra lời khuyên” có thể thành thật nhưng lại mang tính tiêu cực lớn trong các cuộc phỏng vấn. Tại nơi làm việc ở Nhật Bản, việc không thể nói chuyện với ai đó khi gặp vấn đề được coi là một rủi ro lớn. Điều này là do nếu vấn đề không được giải quyết, nó có thể phát triển thành một vấn đề lớn.\n\nNếu bạn đưa ra câu trả lời này, hãy nhớ giải thích lý do tại sao bạn không giỏi và cách khắc phục. Nếu bạn thể hiện thái độ tích cực, chẳng hạn như “Tôi không giỏi tư vấn vì tôi không thoải mái với lời nói, nhưng tôi sẽ chuẩn bị ghi chú và tham khảo ý kiến ​​của bạn” hoặc “Tôi là người nhút nhát, nhưng khi gặp vấn đề, tôi sẽ lấy hết can đảm để yêu cầu giúp đỡ”, bạn có thể cải thiện đánh giá của mình.\n\nCó nhiều lý do khác nhau khiến mọi người không thích tư vấn. Cảm thấy xấu hổ, sợ bị mắng, không hiểu được ngôn ngữ, không biết nói chuyện với ai,… Những nỗi lo lắng này là chung của nhiều người nước ngoài. Tuy nhiên, một công ty tốt sẽ có một môi trường dễ dàng tư vấn cho họ và họ cũng sẽ có hệ thống hỗ trợ cho người nước ngoài.\n\nBạn cũng có thể thực hành tư vấn. Hãy bắt đầu bằng những câu hỏi đơn giản, ghi chú trước, sử dụng ứng dụng dịch thuật, v.v. Ngay cả khi bạn không giỏi tư vấn, bạn vẫn có thể khắc phục được nếu nỗ lực một chút. Trong cuộc phỏng vấn, điều quan trọng là phải nhấn mạnh ý chí vượt qua này."
      },
    ]
  },
];

export default commonQuestions;
