// Chế biến thực phẩm & Nhà máy Bento (Dành cho du học sinh) - Tiếng Việt
window.questions = [
  {"id":5,"icon":"🍱","question":"Bạn có thể đứng làm việc liên tục như xếp cơm hộp và đóng gói thực phẩm không?","choices":[{"text":"Có, đứng làm việc không vấn đề gì","score":1.0,"emoji":"⭕"},{"text":"Tôi sẽ quen dần","score":0.7,"emoji":"🟡"},{"text":"Tôi hơi lo lắng","score":0.5,"emoji":"🟡"},{"text":"Đứng làm việc thì khó với tôi","score":0.0,"emoji":"❌"}],"explanation":"Nhà máy thực phẩm đòi hỏi đứng trên dây chuyền cả ngày. Cần có sức bền thể lực."},
  {"id":6,"icon":"⏰","question":"Bạn có thể làm ca sáng sớm (từ 5 giờ sáng) hoặc ca đêm không?","choices":[{"text":"Có, tôi có thể làm bất kỳ lúc nào","score":1.0,"emoji":"⭕"},{"text":"Tôi sẽ quen dần","score":0.7,"emoji":"🟡"},{"text":"Tôi chỉ muốn làm ban ngày","score":0.5,"emoji":"🟡"},{"text":"Ca sáng sớm hoặc ca đêm không được","score":0.0,"emoji":"❌"}],"explanation":"Nhà máy cơm hộp thường bắt đầu từ 5 giờ sáng. Sản xuất cơm hộp cho cửa hàng tiện lợi có thể chạy suốt đêm."},
  {"id":7,"icon":"🧤","question":"Bạn có thể tuân thủ nghiêm ngặt quy tắc vệ sinh (rửa tay, đeo khẩu trang, mũ, găng tay) không?","choices":[{"text":"Có, quản lý vệ sinh là điều quan trọng nhất","score":1.0,"emoji":"⭕"},{"text":"Có, tôi sẽ tuân thủ","score":0.7,"emoji":"🟡"},{"text":"Hơi phiền nhưng tôi sẽ tuân thủ","score":0.5,"emoji":"🟡"},{"text":"Tôi nghĩ không cần thiết đến vậy","score":0.0,"emoji":"❌"}],"explanation":"Dị vật trong thực phẩm là rủi ro lớn nhất. Một sợi tóc có thể khiến hàng loạt sản phẩm bị hủy."},
  {"id":8,"icon":"🏭","question":"Bạn có thể làm việc nhanh theo tốc độ của băng chuyền không?","choices":[{"text":"Có, tôi có thể theo kịp tốc độ","score":1.0,"emoji":"⭕"},{"text":"Luyện tập thì được","score":0.7,"emoji":"🟡"},{"text":"Tôi hơi lo lắng","score":0.5,"emoji":"🟡"},{"text":"Tôi muốn làm theo nhịp riêng","score":0.0,"emoji":"❌"}],"explanation":"Công việc dây chuyền trong nhà máy thực phẩm đòi hỏi theo kịp tốc độ băng chuyền."},
  {"id":9,"icon":"🔄","question":"Bạn có thể lặp lại cùng một công việc (xếp, đóng gói, kiểm tra) trong nhiều giờ không?","choices":[{"text":"Có, tôi có thể tập trung lặng lẽ","score":1.0,"emoji":"⭕"},{"text":"Không vấn đề gì","score":0.7,"emoji":"🟡"},{"text":"Có thể hơi chán","score":0.5,"emoji":"🟡"},{"text":"Tôi không thích công việc lặp lại","score":0.0,"emoji":"❌"}],"explanation":"Công việc nhà máy thực phẩm lặp đi lặp lại cùng một động tác trong nhiều giờ."},
  {"id":10,"icon":"❄️","question":"Bạn có thể làm việc trong môi trường lạnh (phòng lạnh, phòng đông lạnh) không?","choices":[{"text":"Có, tôi chịu lạnh tốt","score":1.0,"emoji":"⭕"},{"text":"Mặc ấm thì không sao","score":0.7,"emoji":"🟡"},{"text":"Tôi không giỏi chịu lạnh","score":0.5,"emoji":"🟡"},{"text":"Làm việc trong môi trường lạnh là không thể","score":0.0,"emoji":"❌"}],"explanation":"Để bảo quản thực phẩm, bạn có thể phải làm việc trong phòng lạnh dưới 5°C hoặc phòng đông lạnh -20°C."},
  {"id":11,"icon":"📋","question":"Bạn có thể xem hướng dẫn có hình ảnh để xếp và đóng gói chính xác không?","choices":[{"text":"Có, tôi có thể làm đúng theo mẫu","score":1.0,"emoji":"⭕"},{"text":"Có, luyện tập thì được","score":0.7,"emoji":"🟡"},{"text":"Tôi không tự tin lắm","score":0.5,"emoji":"🟡"},{"text":"Tôi không giỏi công việc chi tiết","score":0.0,"emoji":"❌"}],"explanation":"Ngay cả khi không cần tiếng Nhật, bạn cần khả năng tái tạo chính xác từ hướng dẫn có hình ảnh."},
  {"id":12,"icon":"⚠️","question":"Bạn có thể tuân thủ quy tắc an toàn thực phẩm như quản lý chất gây dị ứng không?","choices":[{"text":"Có, an toàn thực phẩm là ưu tiên hàng đầu","score":1.0,"emoji":"⭕"},{"text":"Có, tôi sẽ tuân thủ","score":0.7,"emoji":"🟡"},{"text":"Có vẻ hơi khó","score":0.5,"emoji":"🟡"},{"text":"Tôi nghĩ không cần chú ý nhiều đến vậy","score":0.0,"emoji":"❌"}],"explanation":"Dị ứng thực phẩm có thể đe dọa tính mạng. Sai sót trong xử lý nguyên liệu là không thể chấp nhận."},
  {"id":13,"icon":"🤝","question":"Bạn có thể hợp tác làm việc với nhân viên đa quốc tịch không?","choices":[{"text":"Có, tôi có thể hợp tác với bất kỳ ai","score":1.0,"emoji":"⭕"},{"text":"Có, tôi sẽ cố gắng","score":0.7,"emoji":"🟡"},{"text":"Tôi hơi lo lắng","score":0.5,"emoji":"🟡"},{"text":"Tôi muốn làm việc một mình","score":0.0,"emoji":"❌"}],"explanation":"Nhà máy thực phẩm có nhiều nhân viên nước ngoài từ nhiều quốc gia. Tinh thần hợp tác rất quan trọng."},
  {"id":14,"icon":"📅","question":"Bạn có thể làm việc vào mùa cao điểm (cuối năm, Obon, mùa sự kiện) không?","choices":[{"text":"Có, tôi muốn làm đặc biệt vào mùa cao điểm","score":1.0,"emoji":"⭕"},{"text":"Có, tôi có thể","score":0.7,"emoji":"🟡"},{"text":"Tôi muốn được nghỉ","score":0.5,"emoji":"🟡"},{"text":"Tôi muốn nghỉ vào mùa cao điểm","score":0.0,"emoji":"❌"}],"explanation":"Cuối năm và Obon là thời điểm nhu cầu cơm hộp và đồ ăn sẵn tăng vọt."},
  {"id":15,"icon":"🌟","question":"Bạn có muốn phát triển kỹ năng dài hạn tại nhà máy thực phẩm không?","choices":[{"text":"Có, tôi muốn hướng đến quản lý chất lượng hoặc trưởng nhóm","score":1.0,"emoji":"⭕"},{"text":"Có, tôi muốn tiếp tục một thời gian","score":0.7,"emoji":"🟡"},{"text":"Tôi chưa chắc chắn","score":0.5,"emoji":"🟡"},{"text":"Tôi chỉ muốn làm ngắn hạn","score":0.0,"emoji":"❌"}],"explanation":"Với kinh nghiệm, bạn có thể thăng tiến lên vị trí quản lý chất lượng hoặc trưởng dây chuyền."}
];
