// Food Processing & Bento Factory (For Foreign Students) - English
window.questions = [
  {"id":5,"icon":"🍱","question":"Can you handle standing work such as bento plating and food packaging?","choices":[{"text":"Yes, standing work is no problem","score":1.0,"emoji":"⭕"},{"text":"I can get used to it","score":0.7,"emoji":"🟡"},{"text":"I am a little worried","score":0.5,"emoji":"🟡"},{"text":"Standing work is difficult for me","score":0.0,"emoji":"❌"}],"explanation":"Food factories involve standing on assembly lines all day. Physical stamina is essential."},
  {"id":6,"icon":"⏰","question":"Can you work early morning (from 5 AM) or late night shifts?","choices":[{"text":"Yes, I can work any time","score":1.0,"emoji":"⭕"},{"text":"I can get used to it","score":0.7,"emoji":"🟡"},{"text":"I prefer daytime only","score":0.5,"emoji":"🟡"},{"text":"Early morning or late night shifts are not possible","score":0.0,"emoji":"❌"}],"explanation":"Bento factories often start at 5 AM. Convenience store bento production may run through the night."},
  {"id":7,"icon":"🧤","question":"Can you strictly follow hygiene rules (handwashing, masks, caps, gloves)?","choices":[{"text":"Yes, hygiene management is the most important thing","score":1.0,"emoji":"⭕"},{"text":"Yes, I will follow them","score":0.7,"emoji":"🟡"},{"text":"It is a bit troublesome but I will follow","score":0.5,"emoji":"🟡"},{"text":"I don't think it is that necessary","score":0.0,"emoji":"❌"}],"explanation":"Foreign objects in food are the biggest risk. A single hair can cause mass disposal. Hygiene is absolute."},
  {"id":8,"icon":"🏭","question":"Can you work quickly to match the speed of a conveyor belt?","choices":[{"text":"Yes, I can match the speed","score":1.0,"emoji":"⭕"},{"text":"I can with practice","score":0.7,"emoji":"🟡"},{"text":"I am a little worried","score":0.5,"emoji":"🟡"},{"text":"I want to work at my own pace","score":0.0,"emoji":"❌"}],"explanation":"Assembly line work in food factories requires matching conveyor speed. Delays affect the entire line."},
  {"id":9,"icon":"🔄","question":"Can you repeat the same tasks (plating, packaging, inspection) for hours?","choices":[{"text":"Yes, I can concentrate silently","score":1.0,"emoji":"⭕"},{"text":"No problem","score":0.7,"emoji":"🟡"},{"text":"I might get a little bored","score":0.5,"emoji":"🟡"},{"text":"I don't like repetitive work","score":0.0,"emoji":"❌"}],"explanation":"Food factory work involves repeating the same motions for hours. Focus and patience are required."},
  {"id":10,"icon":"❄️","question":"Can you work in refrigerated or frozen environments?","choices":[{"text":"Yes, I handle cold well","score":1.0,"emoji":"⭕"},{"text":"With proper clothing, I will be fine","score":0.7,"emoji":"🟡"},{"text":"I am not good with cold","score":0.5,"emoji":"🟡"},{"text":"Working in cold environments is not possible","score":0.0,"emoji":"❌"}],"explanation":"To maintain food freshness, you may work in cold rooms below 5°C or freezers at -20°C."},
  {"id":11,"icon":"📋","question":"Can you follow photo-based work instructions to plate and package correctly?","choices":[{"text":"Yes, I can replicate samples accurately","score":1.0,"emoji":"⭕"},{"text":"Yes, I can with practice","score":0.7,"emoji":"🟡"},{"text":"I am not very confident","score":0.5,"emoji":"🟡"},{"text":"I am not good at detailed work","score":0.0,"emoji":"❌"}],"explanation":"Even without Japanese, you need the ability to accurately reproduce work from photo manuals."},
  {"id":12,"icon":"⚠️","question":"Can you follow food safety rules such as allergen management?","choices":[{"text":"Yes, food safety is the top priority","score":1.0,"emoji":"⭕"},{"text":"Yes, I will follow them","score":0.7,"emoji":"🟡"},{"text":"It seems a bit difficult","score":0.5,"emoji":"🟡"},{"text":"I don't think it needs that much attention","score":0.0,"emoji":"❌"}],"explanation":"Food allergies can be life-threatening. Mistakes in handling ingredients are absolutely unacceptable."},
  {"id":13,"icon":"🤝","question":"Can you work cooperatively with multinational staff?","choices":[{"text":"Yes, I can cooperate with anyone","score":1.0,"emoji":"⭕"},{"text":"Yes, I will try my best","score":0.7,"emoji":"🟡"},{"text":"I am a little worried","score":0.5,"emoji":"🟡"},{"text":"I prefer to work alone","score":0.0,"emoji":"❌"}],"explanation":"Food factories employ many foreign workers from various countries. A cooperative attitude is essential."},
  {"id":14,"icon":"📅","question":"Can you work during busy periods (year-end, Obon, event seasons)?","choices":[{"text":"Yes, I want to work especially during busy periods","score":1.0,"emoji":"⭕"},{"text":"Yes, I can handle it","score":0.7,"emoji":"🟡"},{"text":"I would prefer to have time off","score":0.5,"emoji":"🟡"},{"text":"I want time off during busy periods","score":0.0,"emoji":"❌"}],"explanation":"Year-end and Obon holidays see a surge in demand for bento and prepared foods. Workers available during peak times are highly valued."},
  {"id":15,"icon":"🌟","question":"Do you want to build long-term skills at a food factory?","choices":[{"text":"Yes, I want to aim for quality control or team leader","score":1.0,"emoji":"⭕"},{"text":"Yes, I want to continue for a while","score":0.7,"emoji":"🟡"},{"text":"I am not sure yet","score":0.5,"emoji":"🟡"},{"text":"I only want to work short-term","score":0.0,"emoji":"❌"}],"explanation":"With experience, you can advance to quality control or line leader positions."}
];
