// Dishwashing & Kitchen Helper (For Foreign Students) - English
window.questions = [
  {"id":5,"icon":"🍽️","question":"Can you wash dishes and clean cooking equipment for long periods?","choices":[{"text":"Yes, I can keep going with focus","score":1.0,"emoji":"⭕"},{"text":"I can get used to it","score":0.7,"emoji":"🟡"},{"text":"I am a little worried","score":0.5,"emoji":"🟡"},{"text":"Long hours of dishwashing is difficult","score":0.0,"emoji":"❌"}],"explanation":"Dishes come in non-stop at the washing station. Concentration and stamina are needed."},
  {"id":6,"icon":"⏰","question":"Can you handle the rush during lunch and dinner peak hours?","choices":[{"text":"Yes, I find busy times rewarding","score":1.0,"emoji":"⭕"},{"text":"Yes, I can handle it","score":0.7,"emoji":"🟡"},{"text":"I feel a bit pressured","score":0.5,"emoji":"🟡"},{"text":"I struggle during busy times","score":0.0,"emoji":"❌"}],"explanation":"During peak hours, a huge volume of dishes comes in at once. Speed and accuracy are required."},
  {"id":7,"icon":"💧","question":"Are you okay with working with water for extended periods?","choices":[{"text":"Yes, water work is no problem","score":1.0,"emoji":"⭕"},{"text":"With gloves, I will be fine","score":0.7,"emoji":"🟡"},{"text":"I worry about rough hands","score":0.5,"emoji":"🟡"},{"text":"I want to avoid water work","score":0.0,"emoji":"❌"}],"explanation":"Dishwashing constantly involves water. Rubber gloves are standard to prevent rough skin."},
  {"id":8,"icon":"🔪","question":"Can you help with vegetable cutting and food preparation?","choices":[{"text":"Yes, I can work with knives","score":1.0,"emoji":"⭕"},{"text":"I can do simple cutting","score":0.7,"emoji":"🟡"},{"text":"I am a bit nervous about knives","score":0.5,"emoji":"🟡"},{"text":"I don't want to do cooking tasks","score":0.0,"emoji":"❌"}],"explanation":"Kitchen helpers may be asked to help with food prep in addition to dishwashing."},
  {"id":9,"icon":"🧹","question":"Can you keep the kitchen clean and organized?","choices":[{"text":"Yes, I can maintain a clean kitchen","score":1.0,"emoji":"⭕"},{"text":"Yes, I will do it","score":0.7,"emoji":"🟡"},{"text":"Cleaning is not my strong point","score":0.5,"emoji":"🟡"},{"text":"I don't think cleaning is my job","score":0.0,"emoji":"❌"}],"explanation":"Kitchen hygiene is essential for food poisoning prevention. Daily cleaning is mandatory."},
  {"id":10,"icon":"🏃","question":"Can you respond quickly to the chef's instructions?","choices":[{"text":"Yes, I can move quickly","score":1.0,"emoji":"⭕"},{"text":"Yes, I will try my best","score":0.7,"emoji":"🟡"},{"text":"I am not very confident","score":0.5,"emoji":"🟡"},{"text":"I want to work at my own pace","score":0.0,"emoji":"❌"}],"explanation":"Speed is everything in the kitchen. You need to respond promptly to the chef's directions."},
  {"id":11,"icon":"🤝","question":"Can you learn tasks by watching, even without shared language?","choices":[{"text":"Yes, I am good at learning by observation","score":1.0,"emoji":"⭕"},{"text":"Yes, I will try","score":0.7,"emoji":"🟡"},{"text":"I am a little worried","score":0.5,"emoji":"🟡"},{"text":"I need verbal explanations","score":0.0,"emoji":"❌"}],"explanation":"Even in no-Japanese-required dishwashing roles, you need to learn procedures by watching. Observation skills matter."},
  {"id":12,"icon":"⚠️","question":"Can you work safely near hot pots, oil, and knives?","choices":[{"text":"Yes, I will work with safety awareness","score":1.0,"emoji":"⭕"},{"text":"Yes, I will be careful","score":0.7,"emoji":"🟡"},{"text":"I am a bit scared","score":0.5,"emoji":"🟡"},{"text":"I want to avoid dangerous work","score":0.0,"emoji":"❌"}],"explanation":"Kitchens are full of hazards including hot oil and sharp knives. Safety awareness is critical."},
  {"id":13,"icon":"🔄","question":"Do you mind repeating the same tasks every day?","choices":[{"text":"No, I can keep working steadily","score":1.0,"emoji":"⭕"},{"text":"No problem","score":0.7,"emoji":"🟡"},{"text":"I might get a little bored","score":0.5,"emoji":"🟡"},{"text":"I don't like repetitive work","score":0.0,"emoji":"❌"}],"explanation":"Dishwashing and kitchen helper work is a daily routine. Consistent workers are valued."},
  {"id":14,"icon":"📅","question":"Can you work on weekends, holidays, and during busy seasons?","choices":[{"text":"Yes, I want to work when it is busiest","score":1.0,"emoji":"⭕"},{"text":"Yes, I can handle it","score":0.7,"emoji":"🟡"},{"text":"I would prefer time off","score":0.5,"emoji":"🟡"},{"text":"I want weekends and holidays off","score":0.0,"emoji":"❌"}],"explanation":"Restaurants are busiest on weekends and holidays. That is when staff are needed most."},
  {"id":15,"icon":"🌟","question":"Do you want to learn cooking skills in the future?","choices":[{"text":"Yes, I want to become a cook","score":1.0,"emoji":"⭕"},{"text":"Yes, I want to learn basic cooking","score":0.7,"emoji":"🟡"},{"text":"I am not sure yet","score":0.5,"emoji":"🟡"},{"text":"I just want to wash dishes","score":0.0,"emoji":"❌"}],"explanation":"Many people start at the dish station and progress to cooking assistant, then eventually to cook."}
];
