// Rửa bát & Phụ bếp (Dành cho du học sinh) - Tiếng Việt
window.questions = [
  {"id":5,"icon":"🍽️","question":"Bạn có thể rửa bát đĩa và dụng cụ nấu nướng trong thời gian dài không?","choices":[{"text":"Có, tôi có thể tập trung liên tục","score":1.0,"emoji":"⭕"},{"text":"Tôi sẽ quen dần","score":0.7,"emoji":"🟡"},{"text":"Tôi hơi lo lắng","score":0.5,"emoji":"🟡"},{"text":"Rửa bát lâu thì khó","score":0.0,"emoji":"❌"}],"explanation":"Bát đĩa đến liên tục không ngừng. Cần sự tập trung và sức bền."},
  {"id":6,"icon":"⏰","question":"Bạn có thể xử lý được giờ cao điểm trưa và tối không?","choices":[{"text":"Có, giờ bận tôi thấy có động lực hơn","score":1.0,"emoji":"⭕"},{"text":"Có, tôi có thể","score":0.7,"emoji":"🟡"},{"text":"Tôi cảm thấy hơi áp lực","score":0.5,"emoji":"🟡"},{"text":"Giờ bận tôi khó xử lý","score":0.0,"emoji":"❌"}],"explanation":"Giờ cao điểm có lượng bát đĩa khổng lồ đến cùng lúc. Cần tốc độ và chính xác."},
  {"id":7,"icon":"💧","question":"Bạn có chịu được khi làm việc với nước trong thời gian dài không?","choices":[{"text":"Có, làm việc với nước không vấn đề gì","score":1.0,"emoji":"⭕"},{"text":"Đeo găng tay thì không sao","score":0.7,"emoji":"🟡"},{"text":"Tôi lo bị nứt nẻ tay","score":0.5,"emoji":"🟡"},{"text":"Tôi muốn tránh làm việc với nước","score":0.0,"emoji":"❌"}],"explanation":"Rửa bát luôn tiếp xúc với nước. Đeo găng tay cao su là tiêu chuẩn để bảo vệ tay."},
  {"id":8,"icon":"🔪","question":"Bạn có thể phụ cắt rau và chuẩn bị nguyên liệu không?","choices":[{"text":"Có, tôi có thể dùng dao","score":1.0,"emoji":"⭕"},{"text":"Cắt đơn giản thì được","score":0.7,"emoji":"🟡"},{"text":"Tôi hơi lo khi dùng dao","score":0.5,"emoji":"🟡"},{"text":"Tôi không muốn làm việc nấu nướng","score":0.0,"emoji":"❌"}],"explanation":"Phụ bếp có thể được giao chuẩn bị nguyên liệu ngoài rửa bát."},
  {"id":9,"icon":"🧹","question":"Bạn có thể giữ bếp sạch sẽ và gọn gàng không?","choices":[{"text":"Có, tôi có thể duy trì bếp sạch","score":1.0,"emoji":"⭕"},{"text":"Có, tôi sẽ làm","score":0.7,"emoji":"🟡"},{"text":"Dọn dẹp không phải thế mạnh","score":0.5,"emoji":"🟡"},{"text":"Tôi nghĩ dọn dẹp không phải việc của tôi","score":0.0,"emoji":"❌"}],"explanation":"Vệ sinh bếp là nền tảng phòng ngộ độc thực phẩm. Dọn dẹp hàng ngày là bắt buộc."},
  {"id":10,"icon":"🏃","question":"Bạn có thể phản ứng nhanh theo chỉ dẫn của đầu bếp không?","choices":[{"text":"Có, tôi có thể di chuyển nhanh","score":1.0,"emoji":"⭕"},{"text":"Có, tôi sẽ cố gắng","score":0.7,"emoji":"🟡"},{"text":"Tôi không tự tin lắm","score":0.5,"emoji":"🟡"},{"text":"Tôi muốn làm theo nhịp riêng","score":0.0,"emoji":"❌"}],"explanation":"Tốc độ là yếu tố sống còn trong bếp. Cần phản ứng nhanh theo chỉ đạo của đầu bếp."},
  {"id":11,"icon":"🤝","question":"Bạn có thể học việc bằng cách quan sát, ngay cả khi không cùng ngôn ngữ không?","choices":[{"text":"Có, tôi giỏi học bằng quan sát","score":1.0,"emoji":"⭕"},{"text":"Có, tôi sẽ cố gắng","score":0.7,"emoji":"🟡"},{"text":"Tôi hơi lo lắng","score":0.5,"emoji":"🟡"},{"text":"Tôi cần giải thích bằng lời","score":0.0,"emoji":"❌"}],"explanation":"Ngay cả vị trí rửa bát không yêu cầu tiếng Nhật, bạn cần học quy trình bằng cách quan sát."},
  {"id":12,"icon":"⚠️","question":"Bạn có thể làm việc an toàn gần nồi nóng, dầu và dao không?","choices":[{"text":"Có, tôi sẽ làm việc với ý thức an toàn","score":1.0,"emoji":"⭕"},{"text":"Có, tôi sẽ cẩn thận","score":0.7,"emoji":"🟡"},{"text":"Tôi hơi sợ","score":0.5,"emoji":"🟡"},{"text":"Tôi muốn tránh công việc nguy hiểm","score":0.0,"emoji":"❌"}],"explanation":"Bếp đầy rẫy nguy hiểm bao gồm dầu nóng và dao sắc. Ý thức an toàn rất quan trọng."},
  {"id":13,"icon":"🔄","question":"Bạn có ngại lặp lại công việc giống nhau mỗi ngày không?","choices":[{"text":"Không, tôi có thể làm việc đều đặn","score":1.0,"emoji":"⭕"},{"text":"Không vấn đề gì","score":0.7,"emoji":"🟡"},{"text":"Có thể hơi chán","score":0.5,"emoji":"🟡"},{"text":"Tôi không thích công việc lặp lại","score":0.0,"emoji":"❌"}],"explanation":"Rửa bát và phụ bếp là công việc lặp lại hàng ngày. Cần người ổn định và bền bỉ."},
  {"id":14,"icon":"📅","question":"Bạn có thể làm việc vào cuối tuần, ngày lễ và mùa cao điểm không?","choices":[{"text":"Có, tôi muốn làm khi bận nhất","score":1.0,"emoji":"⭕"},{"text":"Có, tôi có thể","score":0.7,"emoji":"🟡"},{"text":"Tôi muốn được nghỉ","score":0.5,"emoji":"🟡"},{"text":"Tôi muốn nghỉ cuối tuần và ngày lễ","score":0.0,"emoji":"❌"}],"explanation":"Nhà hàng bận nhất vào cuối tuần và ngày lễ. Đó là lúc cần nhân viên nhất."},
  {"id":15,"icon":"🌟","question":"Bạn có muốn học kỹ năng nấu nướng trong tương lai không?","choices":[{"text":"Có, tôi muốn trở thành đầu bếp","score":1.0,"emoji":"⭕"},{"text":"Có, tôi muốn học nấu cơ bản","score":0.7,"emoji":"🟡"},{"text":"Tôi chưa chắc chắn","score":0.5,"emoji":"🟡"},{"text":"Tôi chỉ muốn rửa bát","score":0.0,"emoji":"❌"}],"explanation":"Nhiều người bắt đầu từ rửa bát, tiến lên phụ bếp, rồi trở thành đầu bếp."}
];
